version: "2"
services:
  identity:
    image: code.cablelabs.com:4567/micronets/identity-service
    links:
        - freeradius
    depends_on:
        - freeradius
    ports:
      - "3230:3230"
    volumes:
      - ./freeradius/3.0:/etc/freeradius

  freeradius:
    image: freeradius/freeradius-server
    ports:
      - "1812:1812"
    volumes:
      - ./freeradius/3.0:/etc/freeradius



