version: "2"
services:
  identity:
    image: code.cablelabs.com:4567/micronets/identity-service
    build: .
    ports:
      - "3230:3230"

  freeradius:
    image: freeradius
    build: freeradius/
    ports:
      - "1812:1812"



