version: "2"
services:
  identity:
    image: code.cablelabs.com:4567/micronets/identity-service
    build: .
    ports:
      - "3230:3230"
    links:
      - mongo

  mongo:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
