version: "3"
services:
  freeradius:
    image: freeradius/freeradius-server
    ports:
        - "1812:1812"
    volumes:
        - ./freeradius/3.0:/etc/freeradius
  identity:
    build:
          context: ./
          dockerfile: Dockerfile
    image: community.cablelabs.com:4567/micronets-docker/identity-service
    depends_on:
        - freeradius
    ports:
      - "3230:3230"
    volumes:
      - ./freeradius/3.0:/etc/freeradius





